//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb_Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int IdPractica { get; set; }
        public string NombreActividad { get; set; }
        public int IdRegistro { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ControlUsuario ControlUsuario { get; set; }
    }
}
