//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb_Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_prestamo
    {
        public int IdDetallePrestamo { get; set; }
        public int IdPrestamo { get; set; }
        public int IdHerramienta { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual herramienta herramienta { get; set; }
        public virtual prestamo prestamo { get; set; }
    }
}
