//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb_Laboratorios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UDP_CONTROLEntities : DbContext
    {
        public UDP_CONTROLEntities()
            : base("name=UDP_CONTROLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<categoria_herramienta> categoria_herramienta { get; set; }
        public virtual DbSet<ControlUsuario> ControlUsuario { get; set; }
        public virtual DbSet<detalle_prestamo> detalle_prestamo { get; set; }
        public virtual DbSet<Edificio> Edificio { get; set; }
        public virtual DbSet<herramienta> herramienta { get; set; }
        public virtual DbSet<marca_herramienta> marca_herramienta { get; set; }
        public virtual DbSet<prestamo> prestamo { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
