//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb_Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prestamo()
        {
            this.detalle_prestamo = new HashSet<detalle_prestamo>();
        }
    
        public int IdPrestamo { get; set; }
        public string IdUsuario { get; set; }
        public decimal Cantidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> CantidadPU { get; set; }
        public string AreaDeUso { get; set; }
        public Nullable<int> Area { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public int DiasDePrestamo { get; set; }
        public string Notas { get; set; }
        public int IdHerramienta { get; set; }
        public Nullable<int> CalificacionEntrega { get; set; }
    
        public virtual Areas Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_prestamo> detalle_prestamo { get; set; }
        public virtual herramienta herramienta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
